workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

image: python:3.11


stages:
  - build
  - test


before-script:
    script:
        - pip install -r requirements.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy .

black:
  stage: test
  script:
    - black --diff --check .

isort:
  stage: test
  script:
    - isort --check-only --profile black .

flask8:
  stage: test
  script:
    - flake8 .
