version: '2'
services:

  app:
    build:
      context: app
    stop_signal: SIGKILL
    ports:
      - 5000:5000

  generator:
    build:
      context: generator
    stop_signal: SIGKILL

  prometheus:
    image: prom/prometheus:v2.50.1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - 3000:3000