"""added the column user.patronomic

Revision ID: 22ef9ac9829e
Revises: 32a25a718bac
Create Date: 2024-05-10 09:36:48.164437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ef9ac9829e'
down_revision: Union[str, None] = '30913bb914c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronomic', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronomic')
    # ### end Alembic commands ###
