services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=skillbox_db
    ports:
      - 5432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./logs/:/var/log/postgresql
    networks:
      - network
    command: 'postgres -c log_destination=stderr -c logging_collector=on -c log_directory=/var/log/postgresql'

  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      - db

volumes:
  db:
  logs:

networks:
  network:
    external: false
    name: network