services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=skillbox_db
      - log_destination=stderr
      - logging_collector=on
      - log_directory=/var/lib/postgresql/logs
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./logs:/var/lib/postgresql/logs
    networks:
      - network

  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    networks:
      - network
    depends_on:
      - db
#    command: flask --app my_proj run --debug -h 0.0.0.0 -p 8000
    command: gunicorn -w 1 -b 0.0.0.0:8000 'my_proj:create_app()'

volumes:
  db:
  logs:

networks:
  network:
    external: false
    name: network